### ISSUE TITLE
Expose JS_SetInterruptHandler

### ISSUE THREAD

**Issue by pavlukivan** [theduke/quickjs-rs#85]
I'm willing to do it after I'm done with exporting rust classes to js

**Comment by andrieshiemstra** [comment]
don't we just want ALL (relefant) static inlines exposed?

like 
* JS_VALUE_GET_FLOAT64
* JS_VALUE_IS_NAN
* JS_IsNumber
* etc

could we do that programatically from build.rs? (in order to be future proof)
* find all static inline fn in quickjs.h,
* add them to static-functions.c
* add them to lib.rs
* etc

**Comment by pavlukivan** [comment]
@andrieshiemstra I think you replied to the wrong issue/PR

**Comment by andrieshiemstra** [comment]
sorry, i thought JS_SetInterruptHandler was not exposed because it was a static inline function, but JS_SetInterruptHandler is allready available in bindings.rs and thus usable i think.

**Comment by andrieshiemstra** [comment]
moved my idea to #86

**Comment by pavlukivan** [comment]
closing as I don't need this anymore
